import { Capacitor, CapacitorHttp } from '@capacitor/core';
import { ARTISTIC_MODIFIERS, GLOBAL_NEGATIVE_PROMPT } from '../constants';
import { Preset } from '../presets';
import { compressImage } from './imageUtils';
import { apiUrl } from '../utils/apiBase';

const subjectCache: Record<string, string> = {}; // Cache for image subject descriptions

async function geminiRestCall(model: string, payload: any, apiKeyOverride?: string) {
  // Use the platform-injected API_KEY if available, otherwise fallback to GEMINI_API_KEY or override
  const apiKey = apiKeyOverride || process.env.API_KEY || process.env.GEMINI_API_KEY;
  
  if (!apiKey) {
    // If no key is found and we're in the AI Studio environment, try to prompt for one
    if (typeof window !== 'undefined' && window.aistudio) {
      const hasKey = await window.aistudio.hasSelectedApiKey();
      if (!hasKey) {
        await window.aistudio.openSelectKey();
        // After opening the dialog, we must assume success or wait for the user to retry
        throw new Error('Please select an API key in the dialog to continue.');
      }
    }
    throw new Error('Gemini API key not found. Please add it in Settings.');
  }

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`;
  const headers = {
    'Content-Type': 'application/json',
    'x-goog-api-key': apiKey,
  };

  try {
    if (Capacitor.isNativePlatform()) {
      const response = await CapacitorHttp.post({
        url,
        headers,
        data: payload
      });

      if (response.status !== 200) {
        throw new Error(`Gemini API error (${response.status}): ${JSON.stringify(response.data)}`);
      }
      return response.data;
    } else {
      const response = await fetch(`${url}?key=${apiKey}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (!response.ok) {
        const err = await response.text();
        throw new Error(`Gemini API error (${response.status}): ${err}`);
      }
      return await response.json();
    }
  } catch (error: any) {
    console.error("Gemini REST Call Error:", error);
    throw error;
  }
}

function base64ToGenerativePart(base64: string, mimeType: string) {
  return {
    inlineData: {
      data: base64.split(',')[1],
      mimeType
    },
  };
}

export async function generateVisual(
  prompt: string, 
  preset: Preset, 
  base64Image?: string, 
  mimeType?: string,
  activeTab?: string,
  strictMode?: boolean,
  apiKey?: string,
  negativePrompt?: string
): Promise<string> {
  const model = "gemini-2.5-flash-image";
  
  const negPrompt = negativePrompt || preset.negativePrompt;
  const basePromptPart = prompt.includes(preset.basePrompt) ? "" : `. ${preset.basePrompt}`;
  let fullPrompt = `${prompt}${basePromptPart}. ${ARTISTIC_MODIFIERS}. Negative prompt: ${negPrompt}, ${GLOBAL_NEGATIVE_PROMPT}`;
  
  const parts: any[] = [{ text: fullPrompt }];

  if (base64Image && mimeType) {
    const imagePart = base64ToGenerativePart(base64Image, mimeType);
    const poseConstraint = "CRITICAL INSTRUCTION: You MUST maintain the EXACT original pose, position, angle, and composition of the subject from the reference image. Do NOT reposition the subject. Apply the requested style with minimal structural adjustment, acting as a direct style transfer over the original image.";
    
    if (strictMode) {
      const subject = await describeImageSubject(base64Image, mimeType, apiKey);
      fullPrompt = `${poseConstraint} STRICTLY RECREATE this subject: ${subject}. ${prompt}${basePromptPart}. ${ARTISTIC_MODIFIERS}`;
      parts.unshift(imagePart);
      parts[1].text = fullPrompt;
    } else {
      fullPrompt = `${poseConstraint} ${fullPrompt}`;
      parts.unshift(imagePart);
      parts[1].text = fullPrompt;
    }
  }

  const payload = {
    contents: [{ parts }],
    generationConfig: {
      imageConfig: {
        aspectRatio: preset.aspectRatio || '1:1',
        imageSize: "1K"
      }
    }
  };

  try {
    const data = await geminiRestCall(model, payload, apiKey);
    const imagePart = data.candidates?.[0]?.content?.parts?.find((p: any) => p.inlineData);
    
    if (imagePart && imagePart.inlineData) {
      return await compressImage(`data:${imagePart.inlineData.mimeType || 'image/jpeg'};base64,${imagePart.inlineData.data}`, 0.85);
    }
  } catch (error: any) {
    console.error("Gemini Image Generation Error:", error);
    throw new Error(`Gemini image generation failed: ${error.message || 'Unknown error'}`);
  }

  throw new Error("No image generated by Gemini.");
}

export async function describeImageSubject(base64Image: string, mimeType: string, apiKey?: string): Promise<string> {
  const cacheKey = base64Image.substring(0, 500);
  if (subjectCache[cacheKey]) return subjectCache[cacheKey];

  try {
    const response = await fetch(apiUrl('/api/describe-image'), {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ base64Image, mimeType })
    });
    
    if (!response.ok) {
      const err = await response.text();
      throw new Error(`Describe failed: ${err}`);
    }
    
    const data = await response.json();
    const description = data.description || "subject";
    subjectCache[cacheKey] = description;
    return description;
  } catch (error) {
    console.error("Describe Image Error:", error);
    // Fallback to simple subject if server fails
    return "subject";
  }
}

export async function analyzeImage(
  base64Image: string, 
  mimeType: string, 
  activeTab: string = 'vectorize',
  apiKey?: string
): Promise<Omit<Preset, 'name'>> {
  try {
    const response = await fetch(apiUrl('/api/analyze-image'), {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ base64Image, mimeType, activeTab })
    });

    if (!response.ok) {
      const err = await response.text();
      throw new Error(`Analysis failed: ${err}`);
    }

    return await response.json();
  } catch (error) {
    console.error("Analysis Error:", error);
    return {
      basePrompt: "high quality vector art, clean lines",
      negativePrompt: "blurry, pixelated",
      aspectRatio: "1:1"
    };
  }
}
