import { Capacitor, CapacitorHttp } from '@capacitor/core';
import { Preset } from '../presets';
import { compressImage } from './imageUtils';

const subjectCache: Record<string, string> = {}; // Cache for image subject descriptions

async function geminiRestCall(model: string, payload: any, apiKeyOverride?: string) {
  // Use the platform-injected API_KEY if available, otherwise fallback to GEMINI_API_KEY or override
  const apiKey = apiKeyOverride || process.env.API_KEY || process.env.GEMINI_API_KEY;
  
  if (!apiKey) {
    // If no key is found and we're in the AI Studio environment, try to prompt for one
    if (typeof window !== 'undefined' && window.aistudio) {
      const hasKey = await window.aistudio.hasSelectedApiKey();
      if (!hasKey) {
        await window.aistudio.openSelectKey();
        // After opening the dialog, we must assume success or wait for the user to retry
        throw new Error('Please select an API key in the dialog to continue.');
      }
    }
    throw new Error('Gemini API key not found. Please add it in Settings.');
  }

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`;
  const headers = {
    'Content-Type': 'application/json',
    'x-goog-api-key': apiKey,
  };

  try {
    if (Capacitor.isNativePlatform()) {
      const response = await CapacitorHttp.post({
        url,
        headers,
        data: payload
      });

      if (response.status !== 200) {
        throw new Error(`Gemini API error (${response.status}): ${JSON.stringify(response.data)}`);
      }
      return response.data;
    } else {
      const response = await fetch(`${url}?key=${apiKey}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (!response.ok) {
        const err = await response.text();
        throw new Error(`Gemini API error (${response.status}): ${err}`);
      }
      return await response.json();
    }
  } catch (error: any) {
    console.error("Gemini REST Call Error:", error);
    throw error;
  }
}

function base64ToGenerativePart(base64: string, mimeType: string) {
  return {
    inlineData: {
      data: base64.split(',')[1],
      mimeType
    },
  };
}

export async function generateVisual(
  prompt: string, 
  preset: Preset, 
  base64Image?: string, 
  mimeType?: string,
  activeTab?: string,
  strictMode?: boolean,
  apiKey?: string,
  negativePrompt?: string
): Promise<string> {
  const model = "gemini-2.5-flash-image";
  const artisticModifiers = "ultra-precise, technical illustration, sharp edges, high-fidelity vector, 8k resolution, professional graphic design, clean geometry";
  
  const negPrompt = negativePrompt || preset.negativePrompt;
  let fullPrompt = `${prompt}. ${preset.basePrompt}. ${artisticModifiers}. Negative prompt: ${negPrompt}, blurry, low resolution, messy, organic, soft edges`;
  
  const parts: any[] = [{ text: fullPrompt }];

  if (base64Image && mimeType) {
    const imagePart = base64ToGenerativePart(base64Image, mimeType);
    const poseConstraint = "CRITICAL INSTRUCTION: You MUST maintain the EXACT original pose, position, angle, and composition of the subject from the reference image. Do NOT reposition the subject. Apply the requested style with minimal structural adjustment, acting as a direct style transfer over the original image.";
    
    if (strictMode) {
      const subject = await describeImageSubject(base64Image, mimeType, apiKey);
      fullPrompt = `${poseConstraint} STRICTLY RECREATE this subject: ${subject}. ${prompt}. ${preset.basePrompt}. ${artisticModifiers}`;
      parts.unshift(imagePart);
      parts[1].text = fullPrompt;
    } else {
      fullPrompt = `${poseConstraint} ${fullPrompt}`;
      parts.unshift(imagePart);
      parts[1].text = fullPrompt;
    }
  }

  const payload = {
    contents: [{ parts }],
    generationConfig: {
      imageConfig: {
        aspectRatio: preset.aspectRatio || '1:1',
        imageSize: "1K"
      }
    }
  };

  try {
    const data = await geminiRestCall(model, payload, apiKey);
    const imagePart = data.candidates?.[0]?.content?.parts?.find((p: any) => p.inlineData);
    
    if (imagePart && imagePart.inlineData) {
      return await compressImage(`data:${imagePart.inlineData.mimeType || 'image/jpeg'};base64,${imagePart.inlineData.data}`, 0.85);
    }
  } catch (error: any) {
    console.error("Gemini Image Generation Error:", error);
    // Fallback logic could go here if needed
    throw error;
  }

  throw new Error("No image generated by Gemini.");
}

export async function describeImageSubject(base64Image: string, mimeType: string, apiKey?: string): Promise<string> {
  const cacheKey = base64Image.substring(0, 500);
  if (subjectCache[cacheKey]) return subjectCache[cacheKey];

  const model = "gemini-3-flash-preview";
  const imagePart = base64ToGenerativePart(base64Image, mimeType);
  const payload = {
    contents: [{
      parts: [imagePart, { text: "Describe the main subject of this image in a concise phrase for an AI art prompt." }]
    }]
  };

  const data = await geminiRestCall(model, payload, apiKey);
  const description = data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || "subject";
  subjectCache[cacheKey] = description;
  return description;
}

export async function analyzeImage(base64Image: string, mimeType: string, apiKey?: string): Promise<Omit<Preset, 'name'>> {
  const model = "gemini-3-flash-preview";
  const imagePart = base64ToGenerativePart(base64Image, mimeType);
  const prompt = `Analyze this image and generate an AI art prompt that captures its style. Focus on medium, texture, color, and composition. Output only the prompt itself.`;
  const payload = {
    contents: [{
      parts: [imagePart, { text: prompt }]
    }]
  };

  const data = await geminiRestCall(model, payload, apiKey);
  return {
    basePrompt: data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || "vector art",
    aspectRatio: '1:1',
    negativePrompt: 'blurry, noisy, watermark, text, signature',
  };
}
